Add ability to have custom logger
open-cli-tools/concurrently pull request #522
Opened 2024-12-18 06:42 UTC by mwood23

The types allow for a custom logger to be passed in but it's never used.

2024-12-27 11:01 UTC, gustavohenke requested changes
mind fixing the formatting errors?

2024-12-29 04:58 UTC, mwood23 commented
@gustavohenke No problem! Just wanted to make sure you'd like to take the change first. PR updated. Thanks for the awesome lib 🚀

2024-12-31 04:15 UTC, gustavohenke approved these changes

2024-12-31 04:15 UTC, merged

2024-12-31 04:41 UTC, gustavohenke commented
Published as v9.1.2.

Happy new year!